# Generated by Django 4.1.5 on 2023-02-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
    ]
